version: 2

builds:
  - binary: hevy
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: windows
        formats: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

homebrew_casks:
  -
    name: hevy

    alternative_names:
      - hevy@{{ .Version }}
      - hevy@{{ .Major }}

    binaries:
      - hevy

    description: "CLI to manage workouts on Hevy. Includes a skill for ai agents to manage workouts for you."

    install: |
      bin.install hevy
